#!/usr/bin/env php
<?php

namespace Behavioral\Iterator;

require_once "vendor/autoload.php";

$client = new Client();

$client->addItemToTheBucket(new Item("Tights", 150, "darned"));
$client->addItemToTheBucket(new Item("Meat", 250, "rotten"));
$client->addItemToTheBucket(new Item("Bread", 40));

$employee = new Iterator($client->getBucket());

try {
    $employee->iterateItems();
} catch (\Exception $e) {
    echo "Caught exception: {$e->getMessage()}\n";
}
