#!/usr/bin/env php
<?php

namespace Behavioral\Iterator;

require_once "vendor/autoload.php";

$employee = new Employee();
$client   = new Client();

$client->takeABasket(new Basket());
$client->addItemToTheBasket(new Item("Tights", 150, "darned"));
$client->addItemToTheBasket(new Item("Meat", 250, "rotten"));
$client->addItemToTheBasket(new Item("Bread", 40));

try {
    $employee->iterateItems($client->getGoodsFromTheBasket());
} catch (\Exception $e) {
    echo "Caught exception: {$e->getMessage()}\n";
}
